[2025-03-09T05:18:33.081+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4-Entrenamiento_model.validar_modelo manual__2025-03-09T05:18:29.176664+00:00 [queued]>
[2025-03-09T05:18:33.086+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4-Entrenamiento_model.validar_modelo manual__2025-03-09T05:18:29.176664+00:00 [queued]>
[2025-03-09T05:18:33.087+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-09T05:18:33.093+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): validar_modelo> on 2025-03-09 05:18:29.176664+00:00
[2025-03-09T05:18:33.096+0000] {standard_task_runner.py:57} INFO - Started process 368 to run task
[2025-03-09T05:18:33.099+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '4-Entrenamiento_model', 'validar_modelo', 'manual__2025-03-09T05:18:29.176664+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/Entrenamiento_mode.py', '--cfg-path', '/tmp/tmpxhd8xcb7']
[2025-03-09T05:18:33.100+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask validar_modelo
[2025-03-09T05:18:33.131+0000] {task_command.py:410} INFO - Running <TaskInstance: 4-Entrenamiento_model.validar_modelo manual__2025-03-09T05:18:29.176664+00:00 [running]> on host 5a82a0843ee5
[2025-03-09T05:18:33.178+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='4-Entrenamiento_model' AIRFLOW_CTX_TASK_ID='validar_modelo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T05:18:29.176664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T05:18:29.176664+00:00'
[2025-03-09T05:18:33.207+0000] {python.py:183} INFO - Done. Returned value was: {'mejor_modelo': 'KNN', 'train_accuracy': 1.0, 'test_accuracy': 1.0, 'todos_resultados': {'KNN': {'train_accuracy': 1.0, 'test_accuracy': 1.0}, 'LogReg': {'train_accuracy': 1.0, 'test_accuracy': 1.0}, 'LogRegCV': {'train_accuracy': 1.0, 'test_accuracy': 1.0}}}
[2025-03-09T05:18:33.220+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=4-Entrenamiento_model, task_id=validar_modelo, execution_date=20250309T051829, start_date=20250309T051833, end_date=20250309T051833
[2025-03-09T05:18:33.230+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-09T05:18:33.239+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
