[2025-03-09T17:01:26.805+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2-Cargar_data.check_csv_exists manual__2025-03-09T17:01:26.312716+00:00 [queued]>
[2025-03-09T17:01:26.810+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2-Cargar_data.check_csv_exists manual__2025-03-09T17:01:26.312716+00:00 [queued]>
[2025-03-09T17:01:26.810+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-09T17:01:26.818+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_csv_exists> on 2025-03-09 17:01:26.312716+00:00
[2025-03-09T17:01:26.820+0000] {standard_task_runner.py:57} INFO - Started process 320 to run task
[2025-03-09T17:01:26.823+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2-Cargar_data', 'check_csv_exists', 'manual__2025-03-09T17:01:26.312716+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmp2uy175nq']
[2025-03-09T17:01:26.824+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask check_csv_exists
[2025-03-09T17:01:26.856+0000] {task_command.py:410} INFO - Running <TaskInstance: 2-Cargar_data.check_csv_exists manual__2025-03-09T17:01:26.312716+00:00 [running]> on host 2e759f21ee59
[2025-03-09T17:01:26.944+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2-Cargar_data' AIRFLOW_CTX_TASK_ID='check_csv_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T17:01:26.312716+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T17:01:26.312716+00:00'
[2025-03-09T17:01:26.944+0000] {logging_mixin.py:149} INFO - Archivo CSV encontrado: /opt/***/data/penguins_size.csv
[2025-03-09T17:01:26.944+0000] {python.py:183} INFO - Done. Returned value was: True
[2025-03-09T17:01:26.960+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=2-Cargar_data, task_id=check_csv_exists, execution_date=20250309T170126, start_date=20250309T170126, end_date=20250309T170126
[2025-03-09T17:01:26.994+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-09T17:01:27.010+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
