[2025-04-07T19:10:47.909+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T19:10:48.263+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task manual__2025-04-07T19:10:42.613998+00:00 [queued]>
[2025-04-07T19:10:48.278+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task manual__2025-04-07T19:10:42.613998+00:00 [queued]>
[2025-04-07T19:10:48.279+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-07T19:10:48.300+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): decide_next_task> on 2025-04-07 19:10:42.613998+00:00
[2025-04-07T19:10:48.316+0000] {standard_task_runner.py:72} INFO - Started process 1202 to run task
[2025-04-07T19:10:48.329+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '2-Cargar_data', 'decide_next_task', 'manual__2025-04-07T19:10:42.613998+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmp9bxhc00g']
[2025-04-07T19:10:48.335+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask decide_next_task
[2025-04-07T19:10:48.441+0000] {task_command.py:467} INFO - Running <TaskInstance: 2-Cargar_data.decide_next_task manual__2025-04-07T19:10:42.613998+00:00 [running]> on host 7919b389bc8a
[2025-04-07T19:10:48.696+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2-Cargar_data' AIRFLOW_CTX_TASK_ID='decide_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T19:10:42.613998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T19:10:42.613998+00:00'
[2025-04-07T19:10:48.701+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-07T19:10:48.724+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-07T19:10:53.750+0000] {python.py:240} INFO - Done. Returned value was: load_data
[2025-04-07T19:10:53.751+0000] {branch.py:38} INFO - Branch into load_data
[2025-04-07T19:10:53.752+0000] {skipmixin.py:233} INFO - Following branch ('load_data',)
[2025-04-07T19:10:53.771+0000] {skipmixin.py:281} INFO - Skipping tasks [('stop_task', -1)]
[2025-04-07T19:10:53.833+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-07T19:10:53.835+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=2-Cargar_data, task_id=decide_next_task, run_id=manual__2025-04-07T19:10:42.613998+00:00, execution_date=20250407T191042, start_date=20250407T191048, end_date=20250407T191053
[2025-04-07T19:10:53.939+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-07T19:10:53.988+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-07T19:10:53.991+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
