[2025-03-31T23:39:44.852+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T23:39:45.328+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T23:39:30+00:00 [queued]>
[2025-03-31T23:39:45.364+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T23:39:30+00:00 [queued]>
[2025-03-31T23:39:45.364+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T23:39:45.391+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): decide_next_task> on 2025-03-31 23:39:30+00:00
[2025-03-31T23:39:45.431+0000] {standard_task_runner.py:72} INFO - Started process 692 to run task
[2025-03-31T23:39:45.458+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '2-Cargar_data', 'decide_next_task', 'scheduled__2025-03-31T23:39:30+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmpqlkv4xmn']
[2025-03-31T23:39:45.468+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask decide_next_task
[2025-03-31T23:39:45.652+0000] {task_command.py:467} INFO - Running <TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T23:39:30+00:00 [running]> on host 45ab05f75c83
[2025-03-31T23:39:45.913+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2-Cargar_data' AIRFLOW_CTX_TASK_ID='decide_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T23:39:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T23:39:30+00:00'
[2025-03-31T23:39:45.921+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T23:39:45.974+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-31T23:39:51.022+0000] {python.py:240} INFO - Done. Returned value was: load_data
[2025-03-31T23:39:51.022+0000] {branch.py:38} INFO - Branch into load_data
[2025-03-31T23:39:51.023+0000] {skipmixin.py:233} INFO - Following branch ('load_data',)
[2025-03-31T23:39:51.059+0000] {skipmixin.py:281} INFO - Skipping tasks [('stop_task', -1)]
[2025-03-31T23:39:51.158+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T23:39:51.162+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=2-Cargar_data, task_id=decide_next_task, run_id=scheduled__2025-03-31T23:39:30+00:00, execution_date=20250331T233930, start_date=20250331T233945, end_date=20250331T233951
[2025-03-31T23:39:51.317+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T23:39:51.376+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T23:39:51.378+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
