[2025-03-09T03:03:56.225+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_penguins_data.check_csv_exists manual__2025-03-09T03:03:55.268364+00:00 [queued]>
[2025-03-09T03:03:56.234+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_penguins_data.check_csv_exists manual__2025-03-09T03:03:55.268364+00:00 [queued]>
[2025-03-09T03:03:56.234+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-03-09T03:03:56.247+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_csv_exists> on 2025-03-09 03:03:55.268364+00:00
[2025-03-09T03:03:56.251+0000] {standard_task_runner.py:57} INFO - Started process 166 to run task
[2025-03-09T03:03:56.255+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_penguins_data', 'check_csv_exists', 'manual__2025-03-09T03:03:55.268364+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmpv3tkg33b']
[2025-03-09T03:03:56.257+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask check_csv_exists
[2025-03-09T03:03:56.300+0000] {task_command.py:410} INFO - Running <TaskInstance: load_penguins_data.check_csv_exists manual__2025-03-09T03:03:55.268364+00:00 [running]> on host f5e4b6cd6855
[2025-03-09T03:03:56.546+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_penguins_data' AIRFLOW_CTX_TASK_ID='check_csv_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T03:03:55.268364+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T03:03:55.268364+00:00'
[2025-03-09T03:03:56.547+0000] {logging_mixin.py:149} INFO - Archivo CSV encontrado: /opt/***/data/penguins_size.csv
[2025-03-09T03:03:56.547+0000] {python.py:183} INFO - Done. Returned value was: True
[2025-03-09T03:03:56.566+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=load_penguins_data, task_id=check_csv_exists, execution_date=20250309T030355, start_date=20250309T030356, end_date=20250309T030356
[2025-03-09T03:03:56.586+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-09T03:03:56.610+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
