[2025-03-09T03:37:27.436+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2-Cargar_data.load_penguins_data scheduled__2025-03-09T03:32:00+00:00 [queued]>
[2025-03-09T03:37:27.445+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2-Cargar_data.load_penguins_data scheduled__2025-03-09T03:32:00+00:00 [queued]>
[2025-03-09T03:37:27.445+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-09T03:37:27.459+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_penguins_data> on 2025-03-09 03:32:00+00:00
[2025-03-09T03:37:27.463+0000] {standard_task_runner.py:57} INFO - Started process 787 to run task
[2025-03-09T03:37:27.466+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2-Cargar_data', 'load_penguins_data', 'scheduled__2025-03-09T03:32:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmpiapsx_t_']
[2025-03-09T03:37:27.468+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask load_penguins_data
[2025-03-09T03:37:27.516+0000] {task_command.py:410} INFO - Running <TaskInstance: 2-Cargar_data.load_penguins_data scheduled__2025-03-09T03:32:00+00:00 [running]> on host d79f96be65f0
[2025-03-09T03:37:27.594+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2-Cargar_data' AIRFLOW_CTX_TASK_ID='load_penguins_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T03:32:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-09T03:32:00+00:00'
[2025-03-09T03:37:27.596+0000] {logging_mixin.py:149} INFO - Cargando datos de penguins desde /opt/***/data/penguins_size.csv a la tabla penguins...
[2025-03-09T03:37:27.604+0000] {logging_mixin.py:149} INFO - CSV cargado en dataframe, filas: 344
[2025-03-09T03:37:27.606+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-09T03:37:27.606+0000] {base.py:73} INFO - Using connection ID 'mysql_default' for task execution.
[2025-03-09T03:37:27.655+0000] {base.py:73} INFO - Using connection ID 'mysql_default' for task execution.
[2025-03-09T03:37:27.660+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM ***_db.penguins, parameters: None
[2025-03-09T03:37:27.661+0000] {sql.py:384} INFO - Rows affected: 1
[2025-03-09T03:37:27.662+0000] {logging_mixin.py:149} INFO - Carga completada. Total de registros en la tabla: 344
[2025-03-09T03:37:27.662+0000] {python.py:183} INFO - Done. Returned value was: 344
[2025-03-09T03:37:27.681+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=2-Cargar_data, task_id=load_penguins_data, execution_date=20250309T033200, start_date=20250309T033727, end_date=20250309T033727
[2025-03-09T03:37:27.718+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-09T03:37:27.735+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
