[2025-04-01T01:06:48.244+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T01:06:48.369+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: 2-Cargar_data.decide_next_task scheduled__2025-03-31T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_table'}
[2025-04-01T01:06:48.380+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
